#!/usr/bin/env bash
# Configures a new Ubuntu machine by installing
# Nginx which should be listening on port 80
# Serves a page that returns a "Hello World" string

set -e

echo -e "Updating package list and installing Nginx...\n"
sudo apt-get update -y -qq
sudo apt-get install nginx -y

echo -e "\nSetting up Nginx...\n"

# Start Nginx service
sudo service nginx start

# Allow Nginx through the firewall
sudo ufw allow 'Nginx HTTP'

# Give user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
if [ -f /var/www/html/index.nginx-debian.html ]; then
    sudo cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp
fi

# Create new index.html with "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Restart Nginx to apply changes
sudo service nginx restart

echo -e "\nCompleted. ✅ \n"
