#!/usr/bin/env bash
# configures a server to listen on port 80 of all servers active IPv4 IPs

# Replace port 8080 with port 80 in the nginx configuration file
sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default

# Restart the nginx service to apply the configuration changes
sudo service nginx restart

# Clear the contents of /run/nginx.pid without displaying any output
echo "" | sudo dd status=none of=/run/nginx.pid
